version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn -w 2 -b 0.0.0.0:5000 run:app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
